### PR TITLE
Adds a way to change the line color for the gauge.

### PR DESCRIPTION
**Pull request by Iamgoofball**
see title

defaults to the original of #000

### CODE REVIEW

**Review by MrsTonedOne — CHANGES_REQUESTED** [review]
Apply the edit to the JS like I told you, you can't exactly use ractive variables inside of a svg file.

**Comment by konsumer** [comment]
You can. ractive-gauge.js is built from the index.js and SVG file as a template with the `npm run js` command, if you have installed it's dependencies with `npm install`.

**Comment by MrsTonedOne** [comment]
ok, well then you're doing some magic well byond my level

**Comment by Iamgoofball** [comment]
changes to the js reverted since it's handled by js magic

**Comment by konsumer** [comment]
It's not "magic", it's just a fairly standard build system, so you don't have to ensure UMD & hand-edit SVG source embedded in a JS file to change how it looks. I'm going to just implement styling classes for colors (I don't think this lib has a terrible lot of users, so I'm happy to make a quick change if it helps you out.) As a sidenote, if you open the SVG, modify it to look however you want, then run `npm run build` you can have total control over the look of the meter, and it might actually be better, in the end. I will do CSS classes for now, but for more theming changes in the future, it's a better way.

**Comment by konsumer** [comment]
Ok, so now you can use CSS to style it however you like. I included an example in the demo `index.html`.

**Comment by Iamgoofball** [comment]
thanks dude!

**Pull request closed without merging**
