### PR TITLE
Makes the background transparent by default on the SVG.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Using this for a weird implementation of the gauge, needed the background to be transparent.

### CODE REVIEW

**Comment by konsumer** [comment]
Can you make the change in the svg file? The js file is generated.

**Comment by Iamgoofball** [comment]
No problem, lemme do that

**Comment by Iamgoofball** [comment]
There we go, sorry about the messy commit logs. Could probably be fixed with a squash merge though.

**Comment by konsumer** [comment]
No prob! Thanks for the PR

**Pull request merged**
